# Generated by Django 3.2 on 2023-09-02 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
